/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tutorial.guestbookt.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.tutorial.guestbookt.model.GuestbookTEntry;
import com.tutorial.guestbookt.model.GuestbookTEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GuestbookTEntry service. Represents a row in the &quot;GBT_GuestbookTEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GuestbookTEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuestbookTEntryImpl}.
 * </p>
 *
 * @author Andrea Luzzi
 * @see GuestbookTEntryImpl
 * @generated
 */
@JSON(strict = true)
public class GuestbookTEntryModelImpl
	extends BaseModelImpl<GuestbookTEntry> implements GuestbookTEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guestbook t entry model instance should use the <code>GuestbookTEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "GBT_GuestbookTEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"entryId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"message", Types.VARCHAR}, {"guestbookTId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("guestbookTId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GBT_GuestbookTEntry (uuid_ VARCHAR(75) null,entryId LONG not null primary key,name VARCHAR(75) null,email VARCHAR(75) null,message VARCHAR(75) null,guestbookTId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table GBT_GuestbookTEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY guestbookTEntry.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GBT_GuestbookTEntry.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GUESTBOOKTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GuestbookTEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GuestbookTEntry.class;
	}

	@Override
	public String getModelClassName() {
		return GuestbookTEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GuestbookTEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GuestbookTEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookTEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GuestbookTEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GuestbookTEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GuestbookTEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GuestbookTEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GuestbookTEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GuestbookTEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GuestbookTEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GuestbookTEntry.class.getClassLoader(), GuestbookTEntry.class,
			ModelWrapper.class);

		try {
			Constructor<GuestbookTEntry> constructor =
				(Constructor<GuestbookTEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GuestbookTEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GuestbookTEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GuestbookTEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<GuestbookTEntry, Object>>();
		Map<String, BiConsumer<GuestbookTEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GuestbookTEntry, ?>>();

		attributeGetterFunctions.put("uuid", GuestbookTEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<GuestbookTEntry, String>)GuestbookTEntry::setUuid);
		attributeGetterFunctions.put("entryId", GuestbookTEntry::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<GuestbookTEntry, Long>)GuestbookTEntry::setEntryId);
		attributeGetterFunctions.put("name", GuestbookTEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<GuestbookTEntry, String>)GuestbookTEntry::setName);
		attributeGetterFunctions.put("email", GuestbookTEntry::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<GuestbookTEntry, String>)GuestbookTEntry::setEmail);
		attributeGetterFunctions.put("message", GuestbookTEntry::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<GuestbookTEntry, String>)GuestbookTEntry::setMessage);
		attributeGetterFunctions.put(
			"guestbookTId", GuestbookTEntry::getGuestbookTId);
		attributeSetterBiConsumers.put(
			"guestbookTId",
			(BiConsumer<GuestbookTEntry, Long>)
				GuestbookTEntry::setGuestbookTId);
		attributeGetterFunctions.put("groupId", GuestbookTEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GuestbookTEntry, Long>)GuestbookTEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", GuestbookTEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GuestbookTEntry, Long>)GuestbookTEntry::setCompanyId);
		attributeGetterFunctions.put("userId", GuestbookTEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GuestbookTEntry, Long>)GuestbookTEntry::setUserId);
		attributeGetterFunctions.put("userName", GuestbookTEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<GuestbookTEntry, String>)GuestbookTEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", GuestbookTEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GuestbookTEntry, Date>)GuestbookTEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GuestbookTEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GuestbookTEntry, Date>)
				GuestbookTEntry::setModifiedDate);
		attributeGetterFunctions.put("status", GuestbookTEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<GuestbookTEntry, Integer>)GuestbookTEntry::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", GuestbookTEntry::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<GuestbookTEntry, Long>)
				GuestbookTEntry::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", GuestbookTEntry::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<GuestbookTEntry, String>)
				GuestbookTEntry::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", GuestbookTEntry::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<GuestbookTEntry, Date>)GuestbookTEntry::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entryId = entryId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@JSON
	@Override
	public long getGuestbookTId() {
		return _guestbookTId;
	}

	@Override
	public void setGuestbookTId(long guestbookTId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_guestbookTId = guestbookTId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGuestbookTId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("guestbookTId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GuestbookTEntry.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GuestbookTEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GuestbookTEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GuestbookTEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GuestbookTEntryImpl guestbookTEntryImpl = new GuestbookTEntryImpl();

		guestbookTEntryImpl.setUuid(getUuid());
		guestbookTEntryImpl.setEntryId(getEntryId());
		guestbookTEntryImpl.setName(getName());
		guestbookTEntryImpl.setEmail(getEmail());
		guestbookTEntryImpl.setMessage(getMessage());
		guestbookTEntryImpl.setGuestbookTId(getGuestbookTId());
		guestbookTEntryImpl.setGroupId(getGroupId());
		guestbookTEntryImpl.setCompanyId(getCompanyId());
		guestbookTEntryImpl.setUserId(getUserId());
		guestbookTEntryImpl.setUserName(getUserName());
		guestbookTEntryImpl.setCreateDate(getCreateDate());
		guestbookTEntryImpl.setModifiedDate(getModifiedDate());
		guestbookTEntryImpl.setStatus(getStatus());
		guestbookTEntryImpl.setStatusByUserId(getStatusByUserId());
		guestbookTEntryImpl.setStatusByUserName(getStatusByUserName());
		guestbookTEntryImpl.setStatusDate(getStatusDate());

		guestbookTEntryImpl.resetOriginalValues();

		return guestbookTEntryImpl;
	}

	@Override
	public GuestbookTEntry cloneWithOriginalValues() {
		GuestbookTEntryImpl guestbookTEntryImpl = new GuestbookTEntryImpl();

		guestbookTEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		guestbookTEntryImpl.setEntryId(
			this.<Long>getColumnOriginalValue("entryId"));
		guestbookTEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		guestbookTEntryImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		guestbookTEntryImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));
		guestbookTEntryImpl.setGuestbookTId(
			this.<Long>getColumnOriginalValue("guestbookTId"));
		guestbookTEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		guestbookTEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		guestbookTEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		guestbookTEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		guestbookTEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		guestbookTEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		guestbookTEntryImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		guestbookTEntryImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		guestbookTEntryImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		guestbookTEntryImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return guestbookTEntryImpl;
	}

	@Override
	public int compareTo(GuestbookTEntry guestbookTEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), guestbookTEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GuestbookTEntry)) {
			return false;
		}

		GuestbookTEntry guestbookTEntry = (GuestbookTEntry)object;

		long primaryKey = guestbookTEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GuestbookTEntry> toCacheModel() {
		GuestbookTEntryCacheModel guestbookTEntryCacheModel =
			new GuestbookTEntryCacheModel();

		guestbookTEntryCacheModel.uuid = getUuid();

		String uuid = guestbookTEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			guestbookTEntryCacheModel.uuid = null;
		}

		guestbookTEntryCacheModel.entryId = getEntryId();

		guestbookTEntryCacheModel.name = getName();

		String name = guestbookTEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			guestbookTEntryCacheModel.name = null;
		}

		guestbookTEntryCacheModel.email = getEmail();

		String email = guestbookTEntryCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			guestbookTEntryCacheModel.email = null;
		}

		guestbookTEntryCacheModel.message = getMessage();

		String message = guestbookTEntryCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			guestbookTEntryCacheModel.message = null;
		}

		guestbookTEntryCacheModel.guestbookTId = getGuestbookTId();

		guestbookTEntryCacheModel.groupId = getGroupId();

		guestbookTEntryCacheModel.companyId = getCompanyId();

		guestbookTEntryCacheModel.userId = getUserId();

		guestbookTEntryCacheModel.userName = getUserName();

		String userName = guestbookTEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			guestbookTEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			guestbookTEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			guestbookTEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			guestbookTEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			guestbookTEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		guestbookTEntryCacheModel.status = getStatus();

		guestbookTEntryCacheModel.statusByUserId = getStatusByUserId();

		guestbookTEntryCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = guestbookTEntryCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			guestbookTEntryCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			guestbookTEntryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			guestbookTEntryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return guestbookTEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GuestbookTEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GuestbookTEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookTEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((GuestbookTEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GuestbookTEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GuestbookTEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookTEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GuestbookTEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GuestbookTEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _entryId;
	private String _name;
	private String _email;
	private String _message;
	private long _guestbookTId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GuestbookTEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GuestbookTEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("entryId", _entryId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("guestbookTId", _guestbookTId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("entryId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("email", 8L);

		columnBitmasks.put("message", 16L);

		columnBitmasks.put("guestbookTId", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GuestbookTEntry _escapedModel;

}