/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tutorial.liferay.my.gradebook.model.impl;

import com.tutorial.liferay.my.gradebook.model.MyGradebook;
import com.tutorial.liferay.my.gradebook.service.MyGradebookLocalServiceUtil;

/**
 * The extended model base implementation for the MyGradebook service. Represents a row in the &quot;MYGDB_MyGradebook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MyGradebookImpl}.
 * </p>
 *
 * @author Andrea Luzzi
 * @see MyGradebookImpl
 * @see MyGradebook
 * @generated
 */
public abstract class MyGradebookBaseImpl
	extends MyGradebookModelImpl implements MyGradebook {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a my gradebook model instance should use the <code>MyGradebook</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MyGradebookLocalServiceUtil.addMyGradebook(this);
		}
		else {
			MyGradebookLocalServiceUtil.updateMyGradebook(this);
		}
	}

}