/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tutorial.liferay.my.gradebook.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.tutorial.liferay.my.gradebook.model.Gradebook;
import com.tutorial.liferay.my.gradebook.service.GradebookLocalService;
import com.tutorial.liferay.my.gradebook.service.GradebookLocalServiceUtil;
import com.tutorial.liferay.my.gradebook.service.persistence.CoursePersistence;
import com.tutorial.liferay.my.gradebook.service.persistence.GradebookPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the gradebook local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tutorial.liferay.my.gradebook.service.impl.GradebookLocalServiceImpl}.
 * </p>
 *
 * @author Andrea Luzzi
 * @see com.tutorial.liferay.my.gradebook.service.impl.GradebookLocalServiceImpl
 * @generated
 */
public abstract class GradebookLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GradebookLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GradebookLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GradebookLocalServiceUtil</code>.
	 */

	/**
	 * Adds the gradebook to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GradebookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gradebook the gradebook
	 * @return the gradebook that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Gradebook addGradebook(Gradebook gradebook) {
		gradebook.setNew(true);

		return gradebookPersistence.update(gradebook);
	}

	/**
	 * Creates a new gradebook with the primary key. Does not add the gradebook to the database.
	 *
	 * @param gradebookId the primary key for the new gradebook
	 * @return the new gradebook
	 */
	@Override
	@Transactional(enabled = false)
	public Gradebook createGradebook(long gradebookId) {
		return gradebookPersistence.create(gradebookId);
	}

	/**
	 * Deletes the gradebook with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GradebookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gradebookId the primary key of the gradebook
	 * @return the gradebook that was removed
	 * @throws PortalException if a gradebook with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Gradebook deleteGradebook(long gradebookId) throws PortalException {
		return gradebookPersistence.remove(gradebookId);
	}

	/**
	 * Deletes the gradebook from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GradebookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gradebook the gradebook
	 * @return the gradebook that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Gradebook deleteGradebook(Gradebook gradebook) {
		return gradebookPersistence.remove(gradebook);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return gradebookPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Gradebook.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return gradebookPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.tutorial.liferay.my.gradebook.model.impl.GradebookModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return gradebookPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.tutorial.liferay.my.gradebook.model.impl.GradebookModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return gradebookPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return gradebookPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return gradebookPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Gradebook fetchGradebook(long gradebookId) {
		return gradebookPersistence.fetchByPrimaryKey(gradebookId);
	}

	/**
	 * Returns the gradebook matching the UUID and group.
	 *
	 * @param uuid the gradebook's UUID
	 * @param groupId the primary key of the group
	 * @return the matching gradebook, or <code>null</code> if a matching gradebook could not be found
	 */
	@Override
	public Gradebook fetchGradebookByUuidAndGroupId(String uuid, long groupId) {
		return gradebookPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the gradebook with the primary key.
	 *
	 * @param gradebookId the primary key of the gradebook
	 * @return the gradebook
	 * @throws PortalException if a gradebook with the primary key could not be found
	 */
	@Override
	public Gradebook getGradebook(long gradebookId) throws PortalException {
		return gradebookPersistence.findByPrimaryKey(gradebookId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(gradebookLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Gradebook.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("gradebookId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			gradebookLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Gradebook.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"gradebookId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(gradebookLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Gradebook.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("gradebookId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Gradebook>() {

				@Override
				public void performAction(Gradebook gradebook)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, gradebook);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Gradebook.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gradebookPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return gradebookLocalService.deleteGradebook((Gradebook)persistedModel);
	}

	@Override
	public BasePersistence<Gradebook> getBasePersistence() {
		return gradebookPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gradebookPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the gradebooks matching the UUID and company.
	 *
	 * @param uuid the UUID of the gradebooks
	 * @param companyId the primary key of the company
	 * @return the matching gradebooks, or an empty list if no matches were found
	 */
	@Override
	public List<Gradebook> getGradebooksByUuidAndCompanyId(
		String uuid, long companyId) {

		return gradebookPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of gradebooks matching the UUID and company.
	 *
	 * @param uuid the UUID of the gradebooks
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of gradebooks
	 * @param end the upper bound of the range of gradebooks (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching gradebooks, or an empty list if no matches were found
	 */
	@Override
	public List<Gradebook> getGradebooksByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Gradebook> orderByComparator) {

		return gradebookPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the gradebook matching the UUID and group.
	 *
	 * @param uuid the gradebook's UUID
	 * @param groupId the primary key of the group
	 * @return the matching gradebook
	 * @throws PortalException if a matching gradebook could not be found
	 */
	@Override
	public Gradebook getGradebookByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return gradebookPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the gradebooks.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.tutorial.liferay.my.gradebook.model.impl.GradebookModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of gradebooks
	 * @param end the upper bound of the range of gradebooks (not inclusive)
	 * @return the range of gradebooks
	 */
	@Override
	public List<Gradebook> getGradebooks(int start, int end) {
		return gradebookPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of gradebooks.
	 *
	 * @return the number of gradebooks
	 */
	@Override
	public int getGradebooksCount() {
		return gradebookPersistence.countAll();
	}

	/**
	 * Updates the gradebook in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GradebookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gradebook the gradebook
	 * @return the gradebook that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Gradebook updateGradebook(Gradebook gradebook) {
		return gradebookPersistence.update(gradebook);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GradebookLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		gradebookLocalService = (GradebookLocalService)aopProxy;

		_setLocalServiceUtilService(gradebookLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GradebookLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Gradebook.class;
	}

	protected String getModelClassName() {
		return Gradebook.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = gradebookPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		GradebookLocalService gradebookLocalService) {

		try {
			Field field = GradebookLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, gradebookLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CoursePersistence coursePersistence;

	protected GradebookLocalService gradebookLocalService;

	@Reference
	protected GradebookPersistence gradebookPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}